export enum WebSocketTopic {
    SyncStatus = 0,
    Status = 1,
    TPSMetrics = 2,
    TipSelMetric = 3,
    TxZeroValue = 4,
    TxValue = 5,
    Ms = 6,
    PeerMetric = 7,
    ConfirmedMsMetrics = 8,
    Vertex = 9,
    SolidInfo = 10,
    ConfirmedInfo = 11,
    MilestoneInfo = 12,
    TipInfo = 13,
    DBSizeMetric = 14,
    DBCleanup = 15,
    SpamMetrics = 16,
    AvgSpamMetrics = 17
}
