name: Client Build Main/Develop

on: 
  push:
    branches: [main]
    paths:
      - "src/**"
      - ".github/workflows/main.yml"
  pull_request:
    branches: [main]
    paths:
      - "src/**"
      - ".github/workflows/main.yml"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 16.16
        uses: actions/setup-node@v2
        with:
          node-version: "16.16"
      - name: npm 8.18
        run: npm install -g npm@8.18
      - name: Client Build
        run: |
          npm install
          npm run build
